### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by katyukha** [robik/commandr#14]
Hi,

First of all, thanks for great library. It is really awesome)

And, it would be nice, if you release new version that supports dashes in option names. I see that these changes are already on master, but there is no release with this functionality yet.

Thanks

**Comment by katyukha** [comment]
@robik Hi, any new on new release?

Thanks

**Comment by cyrusmsk** [comment]
Maybe consider to send PR to new repo https://github.com/redthing1/cmdex

**Comment by robik** [comment]
Hey @katyukha, I'm really sorry for the delay. Was inactive on GitHub/OSS for quite some time. I am going through past issues/PRs and will try work on this soon!

**Comment by katyukha** [comment]
Hi @robik ,

Thank you.

Also, please check [the way I use this lib](https://github.com/katyukha/Odood/tree/main/subpackages/cli/source/odood/cli), may be it will bring you some ideas for improvements. Base idea was to keep command parameters and command handler code in one place (as close as possible), that is meaningful for cases when you have a lot of commands with a lot of parameters.

Thanks a lot)

**Comment by robik** [comment]
@katyukha Thanks for using this lib! I will try to add new features in my free time. Also, new version is released so this issue can be finally closed 😅

**Comment by robik** [comment]
> Maybe consider to send PR to new repo https://github.com/redthing1/cmdex

Hey @cyrusmsk, this repo was dead for quite some time but I'll try my best to support from now on. If you are interested in contributing to this repository I can make you a contributor :)
