### ISSUE TITLE
Options that could accept no values

### ISSUE THREAD

**Issue by FraMecca** [robik/commandr#3]
One of my utilities does the following:
```
kpd -p 2
[ play song number 2 ]
```
```
kpd -p
[pause or resume playing]
```

At the moment commandr allows only Options (useful in the first case) and Flags (useful for second case).
Can a mixed Option/Flag be added? Or even better a Class that accepts all kind of inputs but requires a validator.

**Comment by robik** [comment]
Related to #2. This would also disable use of arguments and subcommands.

**Comment by FraMecca** [comment]
I'll try to look around the code and understand why a mixed Option/Flag parameter would disable subcommands

**Comment by FraMecca** [comment]
I looked around the code and it is doable changing the structure of the code a lot.
In any case, as of https://github.com/robik/commandr/issues/4#issuecomment-592613774 I found a workaround
