### ISSUE TITLE
Options that accept space separated values

### ISSUE THREAD

**Issue by FraMecca** [robik/commandr#4]
I was wondering if there is a possibility of having a Option that accept multiple space separated values or alternatively a function to specify how many parameters are needed by Option  .
Example:
```
test --delete file1 file2 file3
```

**Comment by robik** [comment]
It is not possible right now, this could be done but that would disable normal arguments and thus subcommands. Will work on it soon.

**Comment by FraMecca** [comment]
In my case I need an option to specify swapping two songs in a playlist:
mediaplayer --swap 1 9

the alternative
mediaplayer --swap 1 --swap 
doesn't seem as explicative

**Comment by FraMecca** [comment]
I found a workaround using argument as the second option.
The issue could be closed
